Repository ZenPrivacy/zen-desktop, pull requests merged in 2024-12, with the labels that each got.

#172 Trusted filter lists
  docs/internal/filter-lists.md
  frontend/src/FilterLists/CreateFilterList/index.css
  frontend/src/FilterLists/CreateFilterList/index.tsx
  frontend/src/FilterLists/index.css
  frontend/src/FilterLists/index.tsx
  frontend/wailsjs/go/models.ts
  internal/cfg/config.go
  internal/cfg/default-config.json
  internal/cfg/migrations.go
  internal/filter/filter.go
  internal/scriptlet/addrule.go
  internal/scriptlet/scriptlet_internal_test.go
  internal/scriptlet/scriptlet_test.go
Labels: in progress

#182 JavaScript rule injection
  internal/app/app.go
  internal/filter/filter.go
  internal/hostmatch/hostmatcher.go
  internal/hostmatch/hostmatcher_test.go
  internal/hostmatch/triestore.go
  internal/htmlrewrite/htmlrewrite_test.go
  internal/jsrule/injector.go
  internal/ruletree/ruletree.go
  internal/scriptlet/injector.go
Labels: enhancement, in progress

#168 Cosmetic rules
  internal/app/app.go
  internal/cosmetic/addrule.go
  internal/cosmetic/injector.go
  internal/cosmetic/sanitizer.go
  internal/cosmetic/sanitizer_test.go
  internal/cosmetic/triestore/triestore.go
  internal/cosmetic/triestore/triestore_test.go
  internal/filter/filter.go
Labels: in progress

#186 Add null checks to jsonPrune
  internal/scriptlet/bundle.js
  scriptlets/src/helpers/jsonPrune.ts
  scriptlets/src/json-prune.test.ts
Labels: bug, review
