Repository ZenPrivacy/zen-desktop, pull requests merged in 2024-11, with the labels that each got.

#138 json-prune and other related scriptlets
  internal/scriptlet/addrule.go
  internal/scriptlet/bundle.js
  scriptlets/Taskfile.yml
  scriptlets/src/helpers/jsonPrune.ts
  scriptlets/src/helpers/request/props.ts
  scriptlets/src/index.ts
  scriptlets/src/json-prune-fetch-response.test.ts
  scriptlets/src/json-prune-fetch-response.ts
  scriptlets/src/json-prune-xhr-response.test.ts
  scriptlets/src/json-prune-xhr-response.ts
  scriptlets/src/json-prune.test.ts
  scriptlets/src/json-prune.ts
  scriptlets/src/prevent-fetch.test.ts
  scriptlets/src/prevent-fetch.ts
  scriptlets/src/prevent-xhr.ts
  scriptlets/src/test/environment.ts
Labels: enhancement, review

#141 Improve linting and testing tasks and CI workflows by adding race con…
  .github/workflows/lint.yml
  Taskfile.yml
Labels: review, tests

#148 Enable AdGuard Base filter by default and add v0.6.0 migration for fi…
  internal/cfg/default-config.json
  internal/cfg/migrations.go
Labels: enhancement

#135 Add filter import export
  frontend/src/FilterLists/ExportFilterList.tsx
  frontend/src/FilterLists/ImportFilterList.tsx
  frontend/src/FilterLists/index.css
  frontend/src/FilterLists/index.tsx
  frontend/wailsjs/go/app/App.d.ts
  frontend/wailsjs/go/app/App.js
  frontend/wailsjs/go/cfg/Config.d.ts
  frontend/wailsjs/go/cfg/Config.js
  internal/app/app.go
  internal/cfg/config.go
Labels: enhancement, review

#153 Add a synchronization channel to ensure App's dependencies get initia…
  internal/app/app.go
  main.go
Labels: review

#139 First party selfupdate
  go.mod
  go.sum
  internal/app/app.go
  internal/cfg/config.go
  internal/cfg/selfupdate.go
  internal/selfupdate/executable.go
  internal/selfupdate/selfupdate.go
  internal/selfupdate/selfupdate_test.go
  internal/selfupdate/uncompress.go
  tasks/build/Taskfile-linux.yml
  tasks/build/Taskfile-windows.yml
Labels: enhancement, review

#158 Implement redaction of sensitive data in logs
  internal/filter/filter.go
  internal/logger/redacted_nonprod.go
  internal/logger/redacted_prod.go
  internal/proxy/proxy.go
  internal/proxy/websocket.go
  internal/scriptlet/injector.go
Labels: review
