Repository ZenPrivacy/zen-desktop, pull requests merged in 2025-04, with the labels that each got.

#276 Add changelog link to the settings footer
  frontend/src/SettingsManager/index.css
  frontend/src/SettingsManager/index.tsx
  frontend/src/i18n/locales/en-US.json
  frontend/src/i18n/locales/ru-RU.json
Labels: enhancement, review

#284 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, review

#283 Fix subdomain handling in the $domain modifier
  internal/networkrules/rule/rule.go
  internal/networkrules/rulemodifiers/domain.go
  internal/networkrules/rulemodifiers/domain_test.go
Labels: bug, review

#287 Set self-update manifests URL to update-manifests.zenprivacy.net
  internal/selfupdate/selfupdate.go
Labels: enhancement, review

#288 Update GitHub repository and code ownership to ZenPrivacy/Zen Privacy Project developers
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  COPYING.md
  LICENSE
  README.md
  build/windows/installer/resources/eula.txt
  docs/internal/filter-lists.md
  docs/internal/localization-guide.md
  frontend/src/MyRules/index.tsx
  frontend/src/SettingsManager/index.tsx
  frontend/src/StartStopButton.tsx
  go.mod
  internal/app/app.go
  internal/app/eventshandler.go
  internal/certstore/diskcertstore.go
  internal/cfg/migrations.go
  internal/cosmetic/injector.go
  internal/cssrule/injector.go
  internal/filter/filter.go
  internal/hostmatch/hostmatcher_test.go
  internal/htmlrewrite/htmlrewrite_test.go
  internal/jsrule/injector.go
  internal/networkrules/exceptionrule/exceptionrule.go
  internal/networkrules/exceptionrule/exceptionrule_test.go
  internal/networkrules/networkrules.go
  internal/networkrules/rule/rule.go
  internal/proxy/proxy.go
  internal/proxy/websocket.go
  internal/scriptlet/injector.go
  internal/scriptlet/injector_test.go
  internal/selfupdate/selfupdate.go
  internal/sysproxy/exclusions/common.txt
  main.go
  proxy/exclusions/windows.txt
  scriptlets/src/set-constant.ts
  scripts/build/upload-manifest.js
  scripts/src/upload-manifest.ts
  tasks/build/Taskfile-darwin.yml
  tasks/build/Taskfile-linux.yml
  tasks/build/Taskfile-windows.yml
  wails.json
Labels: review

#292 Upgrade golangci-lint to v2
  .github/workflows/lint.yml
  .golangci.yml
  internal/cosmetic/sanitizer.go
  internal/scriptlet/arglist.go
Labels: review, dependencies

#290 deps: upgrade golang.org/x/net to v0.38.0, golang.org/x/sys to v0.31.0
  go.mod
  go.sum
Labels: review, dependencies

#291 Automatic CA uninstallation on Windows
  .gitignore
  build/windows/installer/project.nsi
  build/windows/installer/wails_tools.nsh
  internal/app/app.go
  main.go
Labels: enhancement, review

#297 fix: update Hungarian filter list URL in default config
  internal/cfg/default-config.json
  internal/cfg/migrations.go
Labels: review

#298 Add Kazakh language support
  frontend/i18next-parser.config.js
  frontend/src/SettingsManager/LocaleSelector/index.tsx
  frontend/src/SettingsManager/index.tsx
  frontend/src/i18n/index.ts
  frontend/src/i18n/locales/kk-KZ.json
Labels: review

#295 Add mutex to protect node.data
  internal/ruletree/node.go
  internal/ruletree/ruletree.go
Labels: review

#300 Correct translation for 'regional' in kk-KZ localization file
  frontend/src/i18n/locales/kk-KZ.json
Labels: review

#306 Light theme
  frontend/index.html
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/FilterLists/index.css
  frontend/src/SettingsManager/ThemeSelector/index.tsx
  frontend/src/SettingsManager/index.tsx
  frontend/src/common/ThemeManager.tsx
  frontend/src/i18n/locales/de-DE.json
  frontend/src/i18n/locales/en-US.json
  frontend/src/i18n/locales/kk-KZ.json
  frontend/src/i18n/locales/ru-RU.json
  frontend/src/main.tsx
  frontend/src/style.css
Labels: in progress

#312 Fix hostname entry for LastPass and add FreedomPay to exclusions list
  internal/sysproxy/exclusions/common.txt
Labels: review
